<h2>Szczegóły oferty <?= $oferta->numer ?></h2>
<br>
<ul>
    <li>
        <strong>Id oferty</strong>:
        <?=$oferta->id ?>
    </li>
    <li>
        <strong>Typ oferty</strong>:
        <?=$oferta->typ_oferty ?>
    </li>
    <li>
        <strong>Typ nieruchomości</strong>:
        <?=$oferta->typ_nieruchomosci ?>
    </li>
    <li>
        <strong>Powierzchnia</strong>:
        <?=$oferta->powierzchnia ?> m<sup>2</sup>
    </li>
    <li>
        <strong>Cena</strong>:
        <?=$oferta->cena ?> zł
    </li>
</ul>