<?php
$this->headScript()->appendFile($this->basePath('/js/oferty.js'));
$form->setAttribute('action', $this->url('nieruchomosci/oferty', []))
?>

<?= $this->form()->openTag($form) ?>

<h2 class="my-3">Koszyk</h2>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Id oferty</th>
        <th><?= $form->get('typ_oferty')->getLabel() ?></th>
        <th><?= $form->get('typ_nieruchomosci')->getLabel() ?></th>
        <th><?= $form->get('numer')->getLabel() ?></th>
        <th><?= $form->get('powierzchnia')->getLabel() ?></th>
        <th><?= $form->get('cena')->getLabel() ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($oferty as $of): ?>
        <tr>
            <td><?= $of->id ?></td>
            <td><?= $of->typ_oferty ?></td>
            <td><?= $of->typ_nieruchomosci ?></td>
            <td><?= $of->numer ?></td>
            <td><?= $of->powierzchnia ?></td>
            <td><?= $of->cena ?></td>
            <td>
                <a href="<?= $this->url('nieruchomosci/oferty', ['action' => 'szczegoly', 'id' => $of->id]) ?>" title="szczegóły"><i class="fas fa-folder-open"></i></a>
                <a href="<?= $this->url('nieruchomosci/oferty', ['action' => 'drukuj', 'id' => $of->id]) ?>" title="drukuj"><i class="fas fa-print"></i></a>
                <a href="<?= $this->url('nieruchomosci/koszyk', ['action' => 'usun', 'id' => $of->id]) ?>" title="usuń z koszyka" class="aDodajDoKoszyka"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?= $this->paginationControl(
    $oferty,
    'sliding',
    ['partial/paginator.phtml', 'Nieruchomosci'],
    ['route' => 'nieruchomosci/oferty', 'parametry' => $parametry]
)
?>

<?= $this->form()->closeTag($form); ?>