<h1>Szczegóły książki</h1>
<ul>
    <li>
        <strong>Id Książki</strong>:
        <?=$ksiazka['id'] ?>
    </li>
    <li>
        <strong>Autor</strong>:
        <?=$ksiazka['imie'] ?> <?=$ksiazka['nazwisko'] ?>
    </li>
    <li>
        <strong>Tytuł</strong>:
        <?=$ksiazka['tytul'] ?>
    </li>
    <li>
        <strong>Cena</strong>:
        <?=$ksiazka['cena'] ?>
    </li>
    <li>
        <strong>Liczba Stron</strong>:
        <?=$ksiazka['liczba_stron'] ?>
    </li>
    <li>
        <strong>Opis</strong>:
        <br>
        <?=$ksiazka['opis'] ?>
    </li>
</ul>